version: '3'

services:
  apache:
    build:
      context: ./docker/apache
    ports:
      - "8085:80"
    restart: always
    volumes:
      - ./symfony:/var/www/html
      - ~/.composer:/root/.composer